import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
 title:{
  default:"TrendCart || MIRZA",
  template:"%s || TrendCart || MIRZA"
 },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,navbar,navbarBottom,mainslider,footer
}: Readonly<{
  children: React.ReactNode;
  navbar: React.ReactNode;
  navbarBottom: React.ReactNode;
  mainslider: React.ReactNode;
  footer: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-white pb-2 md:pb-0">
          {navbar}
        </div>
        <hr />
        <div className="bg-white">
          {navbarBottom}
        </div>
        <hr />
        <div>
        {children}
        </div>
        <div>
           {footer}
        </div>
        </body>
    </html>
  );
}
